# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_url_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='last_click',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
