# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0003_click_last_click'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_manager.User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
